### ISSUE TITLE
list of gaps and FIXMEs in existing materials

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/curriculum-development#14]
This issue is a list of the subsections that have only bullet points and places where there are "FIXMEs" or other placeholder text in the handbook materials. 

## Bullet point / outlines only
- [ ] I-we-you model
- [ ] collaborative lesson development (note Greg's 10 tips paper)
- [ ] Maintainer recruitment, requirements and time commitment section
- [ ] Instructors roles
- [ ] [Learning objectives](https://carpentries.github.io/curriculum-development/learning-objectives-and-formative-assessment.html) section - convert to more closely match backward design model steps
- [ ] Switch the dataset
- [ ] The stable lesson
- [ ] Pilots and feedback
- [ ] From pre-release to stable
- [ ] Maintanence

## Placeholder text
- [ ] backward design - analogy with drawing.
- [ ] roles / Maintainers - [Include something about accessibility?]
- [ ] Feedback from beta pilots - how given and how incorporated 
- [ ] How to recruit beta pilot Instructors Onboarding?
- [x] How to write RMarkdown
- [ ] Designing challenges ([FIXME: this paragraph might belong better to the learning objective section].)
- [ ] [Add some references to papers that conducted data skills training surveys in different domains?]

## Other
- [ ] Formatting problems with Fill-in-the-blank problems
- [ ] Formatting problems with Use the concept in a different context
- [ ] A1 For Grant supported lessons
- [ ] A2 Transition to officially supported lesson
- [ ] A3 Technical details of lesson template

Resources
https://www.suu.edu/cetl/pdf/abriefoverviewofbackwarddesign.pdf 

Somewhere - * Make a list of out of scope material - this can be used for documenting for “how to say no” aspect of being a maintainer

**Comment by tobyhodges** [comment]
This handbook has now been retired. I am closing all outstanding issues.
