### ISSUE TITLE
add curriculum development handbook to websites and handbook

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/curriculum-development#18]
Where should the Curriculum Development Handbook (CDH) be cross-linked?

- [x] Top level of [Lesson Development section](https://docs.carpentries.org/topic_folders/lesson_development/index.html) in Carpentries Handbook
- [x] The [Roadmap for Lesson Development](https://datacarpentry.org/lessons-incubation/) page on DC website is now out of date. Please remove this page from the drop-down menu and have the url redirect to the front page of the CDH.
- [x] Add the content of the [Roadmap for Lesson Development](https://datacarpentry.org/lessons-incubation/) page in as an issue to this repo, as we will need to integrate some of that information into the CDH.

**Comment by maneesha** [comment]
@ErinBecker I am removing the link to the Roadmap for Lesson Development from the DC site.  Should the new handbook be linked to from the DC site? (and from the LC and SWC sites as well?)

*Note you won't see it live yet; I want to double check a couple of things and will push it live later today*

**Comment by ErinBecker** [comment]
Yes please.

**Comment by ErinBecker** [comment]
Thanks for the work on this @maneesha. Looking great so far.
