### ISSUE TITLE
add section on funding

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/curriculum-development#2]
that describes the resources needed to support inital development and maintenance of the curriculum.

**Comment by jduckles** [comment]
There is this document which lays out some requirements/resource needs, and could use an update to reflect current practices/procedures and actual actionable steps for lesson contributors/grantwriters. http://www.datacarpentry.org/lessons-incubation/

**Comment by tobyhodges** [comment]
This handbook has now been retired, and I am closing all outstanding issues. I hope you are both well ❤️
