### ISSUE TITLE
Integrate "Roadmap for Lesson Development" to the CDH

### ISSUE THREAD

**Issue by maneesha** [carpentries/curriculum-development#20]
The content of the "Roadmap for Lesson Development" has been removed and the link (https://datacarpentry.org/lessons-incubation/) redirects to  https://carpentries.github.io/curriculum-development/index.html.

Per  #18  here may  still be content on this page that needs to be incorporated in to the CDH. The latest content can be viewed [here](https://github.com/datacarpentry/datacarpentry.github.io/blob/96b35a75fb82b4532a8a341d2f07429b98a671c6/pages/lessons-incubation.md).

**Comment by ErinBecker** [comment]
Thank you @maneesha for putting in this issue. There is likely content on that page that can be repurposed for the later chapters in this handbook. I will keep this issue open until we've had a chance to read through that roadmap and see what parts are useful to incorporate.

**Comment by tobyhodges** [comment]
Having reviewed the old [Roadmap for Lesson Development page](https://github.com/datacarpentry/datacarpentry.github.io/blob/96b35a75fb82b4532a8a341d2f07429b98a671c6/pages/lessons-incubation.md) I think the things it covered which are currently missing from the CDH are:

1. lesson retirement.
2. the estimated investment (👩 + 💵) required to develop a new lesson/workshop.

I think it would be easy to drop a subsection on retirement into the end of Chapter 7: The lesson life-cycle, with a note that this applies only to official lessons. 

For the estimate of time/financial investment, I don't see this as exactly belonging in the CDH. Is there somewhere else we can put info like this, for people wanting to enter the Official Track? Another Appendix, to go alongside the one on the Incubator that I'm hoping to introduce in #58? We could then link to this info from the relevant section(s) in C7.

**Comment by tobyhodges** [comment]
This handbook has now been retired. I am closing all outstanding issues.
