### ISSUE TITLE
Unable to find link from published version to GitHub repo

### ISSUE THREAD

**Issue by gvwilson** [carpentries/curriculum-development#21]
On the published version (e.g. https://cdh.carpentries.org/conceptual-elements.html#the-carpentries-mindset-for-curriculum-development) was unable to find a link leading to this GitHub repository - clicking the "edit" button seemed to do it, but that dropped me into the editor for that particular page. Would prefer to see an octocat GitHub logo that brings me to the repo.

**Comment by ErinBecker** [comment]
Thanks for the review @gvwilson. There is a direct link to the GitHub repo from the front page of the handbook (https://cdh.carpentries.org/), but it's true that within each page its only possible to access the editor for that page's content. I think it's worth noting here that that's also the case for our lesson template: 

![Screen Shot 2019-04-04 at 1 48 15 PM](https://user-images.githubusercontent.com/19176319/55587550-71989980-56e0-11e9-9f1e-afd350eb77f2.png)

I'd like to see it be possible to go to the GH repo top level from any page within the Handbook, but don't know how to implement that. Maybe @fmichonneau knows and can comment on the current design choice?
