### ISSUE TITLE
Bibliography issues

### ISSUE THREAD

**Issue by gvwilson** [carpentries/curriculum-development#22]
On pages like https://cdh.carpentries.org/conceptual-elements.html#the-carpentries-mindset-for-curriculum-development, see garbled bibliography entries like this:

![Screen Shot 2019-04-03 at 12 13 31 PM](https://user-images.githubusercontent.com/911566/55495165-50fe1000-560a-11e9-8114-fef81536954f.png)

**Comment by ErinBecker** [comment]
Wow, that's embarrassing. Thanks for catching that! Tagging @fmichonneau to look into this.
