### ISSUE TITLE
lesson-template link to styles repo

### ISSUE THREAD

**Issue by sstevens2** [carpentries/curriculum-development#26]
It is kind of unclear which repo you should import to start.  Think we specifically need to reference and link to the styles repo.

**Comment by sstevens2** [comment]
Maybe a link to here in the technical introductions section? http://carpentries.github.io/lesson-example/setup.html

**Comment by ErinBecker** [comment]
Good point @sstevens2. I'll add this link in and try to clarify this in the text.

**Comment by bencomp** [comment]
Should this be part of #78?

**Comment by tobyhodges** [comment]
This handbook has now been retired. I am closing all outstanding issues.
