### ISSUE TITLE
lost time budgeting estimate

### ISSUE THREAD

**Issue by karenword** [carpentries/curriculum-development#28]
Previously this documentation had a time estimate of 0.5 person-years per 2-day workshop (conservative) for full development. While I recognize that this is a very rough estimate subject to lots of variation, I found it *extremely* valuable in communicating with others about a minimum level of time commitment (and FTE cost) necessary to fully develop a lesson. 

I'm sure you all had a good reason for removing it, but consider this a vote for bringing something like this back somewhere! :)

**Comment by ErinBecker** [comment]
Whoops! We absolutely **do** want to have this information included. I think the idea was to include it in the [lesson life cycle](https://cdh.carpentries.org/the-lesson-life-cycle.html) chapter, but after reading your comment, I think it should be much more front-loaded. What do you think of mentioning this in the first chapter and then having a "Curriculum Development FAQ" section that includes this too? Leaving this open for now - I'm working on this handbook this quarter, so will definitely incorporate the timing back in.

**Comment by tobyhodges** [comment]
This handbook has now been retired. I am closing all outstanding issues.
