### ISSUE TITLE
PDF/epub versions not available

### ISSUE THREAD

**Issue by k-dominik** [carpentries/curriculum-development#37]
Dear Maintainers,

I was just browsing the handbook at https://carpentries.github.io/curriculum-development/ and for more convenient reading of this wonderful material on a Saturday I though about using the epub, or pdf version, for which there exist menu entries. Those links would lead to

* https://carpentries.github.io/curriculum-development/curriculum-development-handbook.epub
* https://carpentries.github.io/curriculum-development/curriculum-development-handbook.pdf

both result in `404`s.

As far as I can tell it should be build with `_build.sh`, but I'm not sure when it should run, or how it would be triggered. Is `tic` running it automagically (could not find any evidence in the travis logs). I don't think I can contribute anything here, as I have never been exposed to tic...
I managed to build the epub version, given your convenient build script, but It would be really great, to have the rendered versions in pdf/epub available online.

Cheers
Dominik

**Comment by ErinBecker** [comment]
Thanks @k-dominik for the issue. @fmichonneau  is looking into this.
