### ISSUE TITLE
Consider adding paragraph in Preface outlining purpose of guide

### ISSUE THREAD

**Issue by angela-li** [carpentries/curriculum-development#38]
It would be helpful to include a short paragraph or bulleted list in the Preface indicating the purpose of the Curriculum Development Handbook. 

I had originally thought this was a more general-purpose guide for all types of curriculum development, but it appears to be more tailored toward producing Carpentries-styles lessons. Perhaps something could be included answering the following questions:

- Who will find this guide useful?
- What is the intended use case of this guide?
- Which sections of the guide are general, and which are specific to the Carpentries?
- What does this guide not include? (and what are other resources that address these?)

**Comment by ErinBecker** [comment]
Thanks @angela-li! This are great questions. I'll take a stab at this in January.

**Comment by tobyhodges** [comment]
This handbook has now been retired. I am closing all outstanding issues.
