### ISSUE TITLE
broken link to video in Chapter 6

### ISSUE THREAD

**Issue by lauracion** [carpentries/curriculum-development#39]
The link "[video recording][maintainer-onboarding-video]" in section 6.3.1 is not working.

**Comment by ErinBecker** [comment]
Thanks for catching this @lauracion. It looks like I put in a placeholder, but never added the actual link to the video. This video was a resource that @libcce created during Library Carpentry Maintainer onboarding last year. @libcce, do you have a link to the video? I just checked out YouTube channel and it's not up there. If you can pass along the link, I can look into getting it up on our channel and publically available. Would be a great resource, especially with @angela-li working on re-booting Maintainer Onboarding.

**Comment by libcce** [comment]
@ErinBecker it might have been a placeholder for a planned onboarding before I left. The only link I have is https://github.com/LibraryCarpentry/governance/blob/master/curriculum/2019-01-20-summary-maintainer-discussions.md which I shared with @angela-li. Would be great to record one of the upcoming onboarding via Zoom and share via The Carpentries YouTube channel.

**Comment by ErinBecker** [comment]
Thanks for clarifying @libcce. I'lll remove the broken link and talk with @angela-li about recording a future Maintainer Onboarding session to share for folks who aren't able to join the real-time sessions.
