### ISSUE TITLE
Minimum dataset licensing requirements?

### ISSUE THREAD

**Issue by Denubis** [carpentries/curriculum-development#41]
A question about the CDH: https://cdh.carpentries.org/designing-challenges.html#picking-a-dataset In picking a dataset, the requirement says CC0. However, there's also a requirement for a real dataset. The dataset I have in mind is CC-BY -- and I'm not quite sure what reasons to provide to the authors to make their dataset CC0. The dataset I'm thinking about using is https://opencontext.org/subjects-search/?proj=85-traces-in-the-lost-landscape#11/-33.6878/150.5127/14/any/Google-Satellite

I'm working on a complete revision of the spreadsheet-to-database lesson. Given that part of the lesson will be "Download the data from Open Context" (with a cheat-backup link in case of issues), how strict is the CC**0** requirement?

**Comment by fmichonneau** [comment]
Thanks for bringing this up. This is not a strict requirement as datasets with this license makes it clear that we re-use, modify, redistribute the data easily.

CC0 is the [recommended license for data](https://wiki.creativecommons.org/wiki/CC0_use_for_data) according to Creative Commons. While [other CC licenses](https://wiki.creativecommons.org/wiki/Data_and_CC_licenses) can be used for data, ensuring correct attribution and citation as the dataset gets modified to make it suitable for teaching can be more complicated. For lessons that are not part of the core official offering, I believe that using a CC-BY dataset is OK.

**Comment by tobyhodges** [comment]
This handbook has now been retired. I am closing all outstanding issues. We address this question in https://carpentries.github.io/lesson-development-training/narrative.html
