### ISSUE TITLE
Places to look for data

### ISSUE THREAD

**Issue by k8hertweck** [carpentries/curriculum-development#64]
The section on [datasets](https://cdh.carpentries.org/designing-challenges.html#picking-a-dataset) describes what to consider when selecting a dataset. It would be great to have a few suggested places to start looking for data. Here are the sites I use when looking for example data:

- [UCI machine learning datasets](https://archive.ics.uci.edu/ml/datasets.php)
  - advantages: large, diverse datasets with attributes and applications already described (chemistry, biology, physics, engineering, social sciences, humanities)
  - disadvantages: licenses not generally mentioned, though citation guidelines are described for each dataset; sometimes metadata is insufficient (but there are often links to other datasets)
- [Data Dryad](https://datadryad.org): data repository primarily for biological datasets associated with published manuscripts
  - advantages: CC0 license, authentic data associated with published research
  - disadvantages: no consistency in formatting or metadata inclusion
- [Tidy Tuesday](https://github.com/rfordatascience/tidytuesday): datasets used for weekly data visualization challenges
  - advantages: very diverse datasets, CC0 license, often with links to news articles; includes ideas for applications of data
  - disadvantages: data aren't always well-curated

I'd be happy to flesh this out more in a PR if this is something folks would like to see in the main text. I can also add some additional verbiage on how to approach extracting tasks (coding, etc) from data.

**Comment by tobyhodges** [comment]
This handbook has now been retired. I am closing all outstanding issues. We provide examples of places to look for data in https://carpentries.github.io/lesson-development-training/narrative.html but if you want to suggest more for the list on that page, a PR wwould be most welcome @k8hertweck
