### ISSUE TITLE
Add a chapter on managing the development process

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/curriculum-development#66]
Based on a discussion with @mkuzak: writing a lesson is much easier if the author(s) schedule regular blocks of time to work on the project (together). It would be good to include some advice about how to approach the process of lesson design/development: how to work together to create a lesson, how often to schedule co-working/sprint sessions, etc.

**Comment by mkuzak** [comment]
Thank you Toby for adding this issue. I am happy to contribute to this chapter.

**Comment by tobyhodges** [comment]
This handbook has now been retired. I am closing all outstanding issues. https://carpentries.github.io/lesson-development-training/collaborating-team.html covers this topic in some detail
