### ISSUE TITLE
Documentation around adding new curricula to core offerings

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/curriculum-development#7]
Once a lesson is developed and ready to be integrated into the core Carpentries curricular offerings, there will be a set of documentation updates needed to make the lesson available for workshop hosts to request.

These include: 
- Adding the curriculum to AMY (e.g. workshop request form)
- Listing the curriculum on the lessons page for the appropriate Lesson Program
- Adding the curriculum to our workshop templates
- Adding to our workshop survey (for the question that asks what workshop you attended)
- others?

These steps will only be applicable for lessons that are being developed to be added to the core Carpentries curriculum stack, and will not be appropriate for all groups that are using this Curriculum Development Handbook. I'm listing this here as a reminder that we will need to add this documentation to the Carpentries Handbook. @maneesha

**Comment by tobyhodges** [comment]
This handbook has now been retired. I am closing all outstanding issues.
