### ISSUE TITLE
Two different versions of CDH online

### ISSUE THREAD

**Issue by alanocallaghan** [carpentries/curriculum-development#70]
- https://carpentries.github.io/curriculum-development/
- https://cdh.carpentries.org/

carp.github.io is 2020-09-07, cdh.carp.org is 2021-04-08

Which one is canonical? Is there a reason for hosting both rather than just redirecting cdh.carp.org to the github io page?

**Comment by zkamvar** [comment]
Thank you for pointing this out!

https://cdh.carpentries.org/ is canonical. It is hosted on Netlify. We used to deploy via TravisCI before they changed the way they run things. I do not know why we did not disable or redirect the github pages site.

**Comment by Alanocallaghan** [comment]
Cool, cheers! Was a bit confused, not sure how but I managed to open the links to both and started seeing missing sections

**Comment by zkamvar** [comment]
Completely understandable!

**Comment by bencomp** [comment]
Both URLs still exist and the github.io one does not redirect to the carpentries.org one. Is that something that can be fixed so that it is clear which URL should be used?

**Comment by alanocallaghan** [comment]
The versions are in line now, and the material will be retired soon, so closing https://github.com/carpentries/curriculum-development/issues/81
