### ISSUE TITLE
deploy broken 

### ISSUE THREAD

**Issue by zkamvar** [carpentries/curriculum-development#75]
The netlify deploy is broken because there are vulnerabilities installed when we try to install the netlify-cli tool from npm.

I am too tired to mess with this now and we might be better off just committing directly to gh-pages until this resolves itself.

**Comment by tobyhodges** [comment]
@zkamvar I do not understand the process sufficiently so could use your insight: is this likely to get fixed without our intervention? I.e. should we just wait? Or is there something I can try to do to address the problem from our side?

**Comment by zkamvar** [comment]
This needs intervention in order to fix. 

The workflow is failing on the step where we attempt to install netlify-cli from npm:

**Comment by zkamvar** [comment]
It turns out that the deploy was broken because there was something not right about our netlify credentials. Instead of poking around to try and figure out why they weren't working, I've gone ahead and enabled gh pages.
