### ISSUE TITLE
Links to (edit) source point to master branch

### ISSUE THREAD

**Issue by bencomp** [carpentries/curriculum-development#77]
The bookdown configuration that appears to be producing links to _View source_ and _Edit_ points to files on the `master` branch in the repository. That causes an 404 error when you want to suggest a change, because `master` was renamed to `main`.
The links to the contribution guide and license also refer to the master branch.

https://github.com/carpentries/curriculum-development/blob/8b855636482fbfce3faa8c0a9b0166bd4de2efcf/_output.yml#L8-L12

**Comment by tobyhodges** [comment]
This handbook has now been retired. I am closing all outstanding issues.
