### ISSUE TITLE
Replace Technological Introductions with link to docs for The Workbench

### ISSUE THREAD

**Issue by bencomp** [carpentries/curriculum-development#78]
Now that all official lessons use The Workbench, the parts of the CDH that refer to the Styles way of working should be rewritten or updated.

**Comment by bencomp** [comment]
I actually think that the technological introductions should be replaced by a link to the Workbench documentation. The CDH seems a good place for the content guidelines, whereas the Workbench supports/implements those guidelines with/in technology. Instead of including instructions for any implementation(s), the instructions of the implementation should refer back to the content guidelines when certain (implementation) choices need to be explained. For example, the why and how of creating learner profiles is part of the CDH; where to put them exactly is part of the Workbench docs, with a link to the CDH for background information.

**Comment by tobyhodges** [comment]
This handbook has now been retired. I am closing all outstanding issues.
